### ISSUE TITLE
Questions: Photos

### ISSUE THREAD

**Issue by mrkvon** [lamanchy/bis#6]
1. How does uploading photos work? I think i can see endpoints for adding urls of photos, but i don't understand how/where to upload photos
2. Where to save info about photos ("Malá ochutnávka")? I can see `event.propagation.invitation_text_about_us`, which seems to be unused, but i don't see a field to save info about photos
3. How to distinguish between main photo (preview) and other photos in propagation? Is it related to field `order` in https://dev.bis.lomic.cz/api/#/frontend/frontend_events_propagation_images_create? How?

Thank you.

_sidenote: I'm also thinking if issues are a right place for these questions. If you @lamanchy open [discussions](https://docs.github.com/en/discussions/quickstart) for this repository, i can put them there. But i don't care, either way is fine for me. Let me know 🙂_

**Comment by lamanchy** [comment]
You pass `data:image/png;filename=<name_of_file_without_extension>;base64,DATA` instead of the url when posting data.

about_us is Malá ochutnávka. I tried to find better name when naming it in English, nothing better came in mind, I can change it, if you have a better idea ;)

There's [models' translations](https://github.com/lamanchy/bis/blob/master/backend/translation/model_translations.yaml), I can expose it through API, if you would be interested to keep the translation in one place. I thought about it, it could be nice, but it could be more harmful. What do you think?

I though the first photo by order would be the main one, but I can create separate field for the main photo. Not quite sure what is better.

_We can keep the discussions here, if you don't mind. It's ok for me. ;)_

**Comment by mrkvon** [comment]
Thank you for explanation. It works, closing.
